/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#c8c6c2",
        "surface": "#141313",
        "on-error": "#690005",
        "primary-container": "#1a1a1a",
        "surface-variant": "#353434",
        "on-primary-container": "#848282",
        "primary-fixed-dim": "#c8c6c5",
        "surface-bright": "#3a3939",
        "primary": "#c8c6c5",
        "inverse-surface": "#e5e2e1",
        "on-primary-fixed": "#1c1b1b",
        "on-tertiary-container": "#c36b4d",
        "on-secondary-container": "#b9b8b4",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary": "#5a1b04",
        "inverse-primary": "#5f5e5e",
        "surface-tint": "#c8c6c5",
        "on-secondary-fixed": "#1b1c19",
        "surface-container-low": "#1c1b1b",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#783118",
        "on-background": "#e5e2e1",
        "secondary": "#c8c6c2",
        "on-primary": "#313030",
        "primary-fixed": "#e5e2e1",
        "on-surface-variant": "#c4c7c7",
        "on-error-container": "#ffdad6",
        "surface-dim": "#141313",
        "outline": "#8e9192",
        "inverse-on-surface": "#313030",
        "secondary-fixed": "#e4e2dd",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e0e",
        "tertiary": "#ffb59d",
        "secondary-container": "#494946",
        "surface-container": "#201f1f",
        "tertiary-fixed-dim": "#ffb59d",
        "on-secondary": "#30312e",
        "on-surface": "#e5e2e1",
        "surface-container-highest": "#353434",
        "surface-container-high": "#2b2a2a",
        "outline-variant": "#444748",
        "on-primary-fixed-variant": "#474746",
        "background": "#141313",
        "tertiary-container": "#370b00",
        "on-secondary-fixed-variant": "#474444"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding-mobile": "24px",
        "container-padding-desktop": "64px",
        "gutter": "24px",
        "unit": "4px",
        "section-gap": "80px"
      },
      fontFamily: {
        'reddit-sans': ['"Reddit Sans"', 'sans-serif'],
        'noto-sans': ['"Noto Sans"', 'sans-serif'],
        'noto-sans-gujarati': ['"Noto Sans Gujarati"', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'montserrat': ['Montserrat', 'sans-serif'],
        "label-sm": ["Geist"],
        "body-md": ["DM Sans"],
        "body-lg": ["DM Sans"],
        "headline-lg": ["Libre Caslon Text"],
        "headline-lg-mobile": ["Libre Caslon Text"],
        "headline-xl": ["Libre Caslon Text"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "0.03em", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "0.05em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
